local M = {}

---Define the plugin highlight groups for the current background.
function M.setup()
  local is_light = vim.o.background == 'light'

  if is_light then
    vim.api.nvim_set_hl(0, 'PiBorder', { fg = '#9E9E9E', default = true })
    vim.api.nvim_set_hl(0, 'PiBackground', { link = 'Normal', default = true })
    vim.api.nvim_set_hl(0, 'PiSessionDescription', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'PiMention', { link = 'Special', default = true })
    vim.api.nvim_set_hl(0, 'PiToolBorder', { fg = '#B0BEC5', nocombine = true, default = true })
    vim.api.nvim_set_hl(0, 'PiMessageRoleAssistant', { link = 'Special', default = true })
    vim.api.nvim_set_hl(0, 'PiMessageRoleUser', { link = 'Question', default = true })
    vim.api.nvim_set_hl(0, 'PiDiffAdd', { bg = '#E8F5E8', default = true })
    vim.api.nvim_set_hl(0, 'PiDiffDelete', { bg = '#FFEBEE', default = true })
    vim.api.nvim_set_hl(0, 'PiDiffAddText', { link = 'Added', default = true })
    vim.api.nvim_set_hl(0, 'PiDiffDeleteText', { link = 'Removed', default = true })
    vim.api.nvim_set_hl(0, 'PiDiffGutter', { fg = '#757575', bg = '#F5F5F5', default = true })
    vim.api.nvim_set_hl(0, 'PiDiffAddGutter', { fg = '#2E7D32', bg = '#F1FAF1', default = true })
    vim.api.nvim_set_hl(0, 'PiDiffDeleteGutter', { fg = '#C62828', bg = '#FFF1F3', default = true })
    vim.api.nvim_set_hl(0, 'PiRevertBorder', { bg = '#FF9E3B', default = true })
    vim.api.nvim_set_hl(0, 'PiPermissionBorder', { fg = '#FF9E3B', nocombine = true, default = true })
    vim.api.nvim_set_hl(0, 'PiAgentPlan', { bg = '#2196F3', fg = '#FFFFFF', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiAgentBuild', { bg = '#757575', fg = '#FFFFFF', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiAgentCustom', { bg = '#90A4AE', fg = '#FFFFFF', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiContextualActions', { bg = '#90A4AE', fg = '#1976D2', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiInputLegend', { bg = '#757575', fg = '#424242', bold = false, default = true })
    vim.api.nvim_set_hl(0, 'PiHint', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'PiVariant', { link = '@attribute', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiGuardDenied', { fg = '#F44336', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiContextBar', { fg = '#3b4261', default = true })
    vim.api.nvim_set_hl(0, 'PiContextFile', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'PiContextCurrentFile', { link = 'PiContext', default = true })
    vim.api.nvim_set_hl(0, 'PiContextCurrentFileNotUpdated', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'PiContextAgent', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'PiContextSelection', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'PiContextError', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'PiContextWarning', { link = 'DiagnosticWarn', default = true })
    vim.api.nvim_set_hl(0, 'PiContextInfo', { link = 'DiagnosticInfo', default = true })
    vim.api.nvim_set_hl(0, 'PiContextSwitchOn', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'PiPickerTime', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'PiDebugText', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'PiReference', { fg = '#5F7896', default = true })
    vim.api.nvim_set_hl(0, 'PiSymbolReference', { link = 'Identifier', default = true })
    vim.api.nvim_set_hl(0, 'PiReasoningText', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(
      0,
      'PiAssistantInterimText',
      { fg = '#757575', italic = true, bold = false, nocombine = true, default = true }
    )
    vim.api.nvim_set_hl(0, 'PiPermissionTitle', { fg = '#FF9E3B', default = true })
    vim.api.nvim_set_hl(0, 'PiDialogOptionHover', { bg = '#E3F2FD', fg = '#1976D2', default = true })
    vim.api.nvim_set_hl(0, 'PiQuestionOption', { link = 'Normal', default = true })
    vim.api.nvim_set_hl(0, 'PiQuestionBorder', { fg = '#E3F2FD', default = true })
    vim.api.nvim_set_hl(0, 'PiQuestionTitle', { link = '@label', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiQuestionTabActive', { bg = '#E3F2FD', fg = '#1976D2', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiQuestionTabDone', { fg = '#2E7D32', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiQuestionTabPending', { fg = '#757575', default = true })
    vim.api.nvim_set_hl(0, 'PiQuestionKeyHint', { fg = '#1976D2', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiChangedLines', { bg = '#FFF3BF', default = true })
  else
    vim.api.nvim_set_hl(0, 'PiBorder', { fg = '#616161', default = true })
    vim.api.nvim_set_hl(0, 'PiBackground', { link = 'Normal', default = true })
    vim.api.nvim_set_hl(0, 'PiSessionDescription', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'PiMention', { link = 'Special', default = true })
    vim.api.nvim_set_hl(0, 'PiToolBorder', { fg = '#3b4261', nocombine = true, default = true })
    vim.api.nvim_set_hl(0, 'PiRevertBorder', { bg = '#FF9E3B', default = true })
    vim.api.nvim_set_hl(0, 'PiPermissionBorder', { fg = '#FF9E3B', nocombine = true, default = true })
    vim.api.nvim_set_hl(0, 'PiMessageRoleAssistant', { link = 'Added', default = true })
    vim.api.nvim_set_hl(0, 'PiMessageRoleUser', { link = 'Question', default = true })
    vim.api.nvim_set_hl(0, 'PiDiffAdd', { bg = '#2B3328', default = true })
    vim.api.nvim_set_hl(0, 'PiDiffDelete', { bg = '#43242B', default = true })
    vim.api.nvim_set_hl(0, 'PiDiffAddText', { link = 'Added', default = true })
    vim.api.nvim_set_hl(0, 'PiDiffDeleteText', { link = 'Removed', default = true })
    vim.api.nvim_set_hl(0, 'PiDiffGutter', { fg = '#6B7280', bg = '#252631', default = true })
    vim.api.nvim_set_hl(0, 'PiDiffAddGutter', { fg = '#A5D6A7', bg = '#344032', default = true })
    vim.api.nvim_set_hl(0, 'PiDiffDeleteGutter', { fg = '#EF9A9A', bg = '#52303A', default = true })
    vim.api.nvim_set_hl(0, 'PiAgentPlan', { bg = '#61AFEF', fg = '#FFFFFF', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiAgentBuild', { bg = '#616161', fg = '#FFFFFF', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiAgentCustom', { bg = '#3b4261', fg = '#FFFFFF', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiContextualActions', { bg = '#3b4261', fg = '#61AFEF', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiInputLegend', { link = '@label', bold = false, default = true })
    vim.api.nvim_set_hl(0, 'PiHint', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'PiVariant', { link = '@attribute', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiGuardDenied', { fg = '#EF5350', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiContextBar', { fg = '#3b4261', default = true })
    vim.api.nvim_set_hl(0, 'PiContextFile', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'PiContextCurrentFile', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'PiContextCurrentFileNotUpdated', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'PiContextAgent', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'PiContextSelection', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'PiContextError', { link = 'DiagnosticError', default = true })
    vim.api.nvim_set_hl(0, 'PiContextWarning', { link = 'DiagnosticWarn', default = true })
    vim.api.nvim_set_hl(0, 'PiContextSwitchOn', { link = '@label', default = true })
    vim.api.nvim_set_hl(0, 'PiPickerTime', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'PiDebugText', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(0, 'PiReference', { fg = '#8AA6C8', default = true })
    vim.api.nvim_set_hl(0, 'PiSymbolReference', { link = 'Identifier', default = true })
    vim.api.nvim_set_hl(0, 'PiReasoningText', { link = 'Comment', default = true })
    vim.api.nvim_set_hl(
      0,
      'PiAssistantInterimText',
      { fg = '#7F8490', italic = true, bold = false, nocombine = true, default = true }
    )
    vim.api.nvim_set_hl(0, 'PiPermissionTitle', { fg = '#FF9E3B', default = true })
    vim.api.nvim_set_hl(0, 'PiDialogOptionHover', { bg = '#2B3A5A', fg = '#61AFEF', default = true })
    vim.api.nvim_set_hl(0, 'PiQuestionOption', { link = 'Normal', default = true })
    vim.api.nvim_set_hl(0, 'PiQuestionBorder', { fg = '#2B3A5A', default = true })
    vim.api.nvim_set_hl(0, 'PiQuestionTitle', { link = '@label', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiQuestionTabActive', { bg = '#2B3A5A', fg = '#61AFEF', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiQuestionTabDone', { fg = '#98C379', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiQuestionTabPending', { fg = '#7F8490', default = true })
    vim.api.nvim_set_hl(0, 'PiQuestionKeyHint', { fg = '#61AFEF', bold = true, default = true })
    vim.api.nvim_set_hl(0, 'PiChangedLines', { bg = '#3D3520', default = true })
  end
end

return M
